db:
  schema: TEST_SCHEMA_2
  audit:
    table: CONFIG_MAP_2
    mapping_table: COMFIG_MAP_AUDIT_2
    audit_mode: C
    audit_retention: 1 #month

spring:
  datasource:
    url: jdbc:h2:file:/data/demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


